{
 "title": "Pratica 07 - Monitoramento Flask",
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisicoes GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{method=\"GET\"}"
    }
   ]
  },
  {
   "title": "Tempo medio de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[5m]) / rate(flask_http_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Erros HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[30s]))"
    }
   ]
  }
 ]
}