name: CI - Pratica 04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Primeiro job
        run: echo "Primeiro job de teste executado com sucesso"

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Flask
        run: pip install flask

      - name: Executar testes unitarios
        run: python -m unittest -v tests/appTest.py
